### ISSUE TITLE
List of channel specific commands

### ISSUE THREAD

**Issue by taylorsamy** [Kalbintion/Kdkbot#2]
I want to be able to list only the commands that have been defined by mods in a channel. I don't want to see all the default commands in this list.

**Comment by Kalbintion** [comment]
_commands list *_ or _commands list <#>_ will remove some of the built-in commands but commands such as ban, etc, are technically custom commands and show up when a specific rank is requested. Internal commands like quote, perm, etc won't show in that particular case.

**Comment by Kalbintion** [comment]
Feature is being worked on, but a bit of code will need to be re-written to act upon this better.

**Comment by taylorsamy** [comment]
Danke Kalby <3

**Comment by Kalbintion** [comment]
Feature implemented, _commands list [custom | c] [rank]_ is now the command format.
